### PR TITLE
Fix: fixes wallet creation without changeDescriptor and getLastUnusedAddress method

### LINKED ISSUE #17: createWallet failing with only descriptor and no changeDescriptor
Hi @BitcoinZavior, Kudos for the new changes to the package. Everything I tested seems to work fine so far. Just having an issue with creating wallet.

If we try to create wallet as follows:

```dart
  await wallet1.createWallet(
    network: Network.TESTNET,
    descriptor: descriptor,
    blockchainConfig: electrumConfig,
  );
```
It throws  this error: ```Unhandled Exception: WalletException.unexpected(e: called `Result::unwrap()` on an `Err` value: Descriptor(Miniscript(Unexpected("null(0 args) while parsing Miniscript"))))```. I don't think this is intended behaviour. 

This is happening due to [this line](https://github.com/LtbLightning/bdk-flutter/blob/main/lib/src/root.dart#L35). Here we should check if changeDescriptor or descriptor is not null or empty before calling ```toString()```.

### PR DESCRIPTION
**Pull request by MrUnfunny**
Fixed wallet creation and getLastUnusedAddress

fixes #17

### CODE REVIEW

File: lib/src/root.dart [hunk 1]
```diff
@@ -32,8 +32,8 @@ class BdkFlutter {
       // }
       if (descriptor != null || changeDescriptor != null) {
```
Comment (MrUnfunny) [inline lib/src/root.dart:33]: @BitcoinZavior Do we need to check if changeDescriptor is not null?

**Review by BitcoinZavior — APPROVED** [review]
